# Generated by Django 4.2 on 2025-07-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='total_learners',
            field=models.IntegerField(default=0),
        ),
    ]
